version: '3'
services:
  memcached:
    image: memcached:alpine
    ports:
      - "11212:11211"
    container_name: memecached

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql_database
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pw
    ports:
      - "13306:3306"
    volumes:
      - ./mysql/initial.sql:/docker-entrypoint-initdb.d/initial.sql
    container_name: mysql

  nginx:
    build: ./nginx
    ports:
      - "33780:80"
      - "33443:443"
    volumes:
      - ./app:/var/www/html/public
    container_name: nginx

  web:
    build: ./php-fpm73
    volumes:
      - ./app:/var/www/html/public
    environment:
      DATABASE_HOST: 'mysql'
      DATABASE_NAME: 'mysql_database'
      DATABASE_USER: 'mysql_user'
      DATABASE_PASSWORD: 'mysql_pw'
    container_name: web