version: '3'

services:
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql-variables.env
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
    container_name: cluster-mysql
  
  mysql-exporter:
    image: prom/mysqld-exporter
    env_file:
      - ./env/mysql-exporter-variables.env
    ports:
      - "39104:9104"
    depends_on:
      - mysql
    command: ["--collect.info_schema.processlist", "--collect.info_schema.innodb_metrics", "--collect.info_schema.tablestats", "--collect.info_schema.tables", "--collect.info_schema.userstats"]
    container_name: cluster-mysql-exporter

  memcached:
    image: memcached:alpine
    container_name: cluster-memcached

  memcached-exporter:
    image: quay.io/prometheus/memcached-exporter
    ports:
      - "39150:9150"
    depends_on:
      - memcached
    command: ["--memcached.address", "memcached:11211"]
    container_name: cluster-memcached-exporter

    
# services:
#   memcached:
#     image: memcached:alpine
#     ports:
#       - "11212:11211"
#     container_name: memcached

#   mysql:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: mysql_database
#       MYSQL_USER: mysql_user
#       MYSQL_PASSWORD: mysql_pw
#     ports:
#       - "13306:3306"
#     volumes:
#       - ./mysql/initial.sql:/docker-entrypoint-initdb.d/initial.sql
#     container_name: mysql

#   nginx:
#     build: ./nginx
#     ports:
#       - "33780:80"
#       - "33443:443"
#     volumes:
#       - ./app:/var/www/html/public
#     container_name: nginx

#   web:
#     build: ./php
#     ports:
#       - "9000:9000"
#     volumes:
#       - ./app:/var/www/html/public
#     environment:
#       DATABASE_HOST: 'mysql'
#       DATABASE_NAME: 'mysql_database'
#       DATABASE_USER: 'mysql_user'
#       DATABASE_PASSWORD: 'mysql_pw'
#     container_name: web
    