{
 "title": "PHP-FPM",
 "description": "PHP-FPM monitoring dashboard",
 "tags": [ "php" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "label_values(phpfpm_accepted_connections, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Process Utilisation",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg((sum(phpfpm_active_processes{instance=\"$Host\"})*100) / sum (phpfpm_total_processes{instance=\"$Host\"}))"
    }
   ]
  },
  {
   "title": "Max Children reached",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(phpfpm_max_children_reached{instance=\"$Host\"})"
    }
   ]
  },
  {
   "title": "Accepted Connections",
   "type": "singlestat",
   "description": "Total number of accepted connections",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (instance)(rate(phpfpm_accepted_connections{instance=\"$Host\"}[1m])*60)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Duration by process",
   "type": "graph",
   "description": "Number of requests that exceed request_slowlog_timeout",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_process_request_duration{instance=\"$Host\"}) by (pid_hash)",
     "legendFormat": "{{pid_hash}}"
    }
   ]
  },
  {
   "title": "# of processes by state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_process_state{instance=\"$Host\"}) by (state)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(phpfpm_process_state{instance=\"$Host\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Slow Requests",
   "type": "graph",
   "description": "Number of requests that exceed request_slowlog_timeout",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_slow_requests{instance=\"$Host\"}) by (instance)",
     "legendFormat": "{{instance}} - {{state}}"
    }
   ]
  },
  {
   "title": "Max Children Reached",
   "type": "graph",
   "description": "Number of times the process limit has been reached",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_max_children_reached{instance=\"$Host\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Process Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent", "label": "Process utilisation" }
   ],
   "targets": [
    {
     "expr": "avg((sum(phpfpm_active_processes{instance=\"$Host\"})*100) / sum (phpfpm_total_processes{instance=\"$Host\"}))",
     "legendFormat": "Process utilisation"
    }
   ]
  },
  {
   "title": "Process Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_total_processes{instance=\"$Host\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Listen Queue Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SUM(phpfpm_listen_queue{instance=\"$Host\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Max Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SUM(phpfpm_max_active_processes{instance=\"$Host\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Listen Queue Max Connections",
   "type": "graph",
   "description": "Max number of connections the listen queue has reached since FPM start",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_max_listen_queue{instance=\"$Host\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Listen Queue Length Connections",
   "type": "graph",
   "description": "The length of the socket queue, dictating maximum number of pending connections",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SUM(phpfpm_listen_queue_length{instance=\"$Host\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}