groups:
  - name: Mysql
    rules:
    - alert: Mysql status
      expr: mysql_up < 1
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Mysql is down"
        description: "Mysql on {{ $labels.instance }} is currently down."

  - name: Node
    rules:
    - alert: Disk is almost full
      expr: (node_filesystem_avail_bytes{mountpoint="/"}/node_filesystem_size_bytes{mountpoint="/"}) < 0.5
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Disk is less then 50%"
        description: 'Disk will be full on {{ $labels.instance }}. Now available {{ $value | printf "%.2f" }}%.'